# Configuration des services
services:
  # Liste des services internes (HuggingFace Spaces)
  names:    
    - "jefraudai/docsify"
    - "jefraudai/slidev"
    - "jefraudai/consumer"
    - "jefraudai/producer"
  # Liste des satellites (HuggingFace Spaces)
  satellites:
    - "mlflai/MLflow"